// packages/web-components/components/src/tag/index.ts
import { LitElement, css, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import "iconify-icon";

@customElement("u-tag")
export class UTag extends LitElement {
  @property()
  type?: "default" | "success" | "info" | "warning" | "error" = "default";

  @property({ type: Boolean })
  closable? = false;

  _dispatchClose(e: Event) {
    e.preventDefault();
    this.dispatchEvent(new CustomEvent("close"));
  }

  render() {
    return html`
      <span class="tag type-${this.type}">
        <slot></slot>

        ${this.closable
          ? html`<iconify-icon
              icon="material-symbols:close"
              width="14"
              height="14"
              style="margin-left: 2px; cursor: pointer"
              @click=${this._dispatchClose}
            ></iconify-icon>`
          : undefined}
      </span>
    `;
  }

  static styles = css`
    :host {
      display: inline-block;
    }

    .tag {
      display: inline-flex;
      align-items: center;
      margin-right: 6px;
      padding: 4px 8px;

      border-width: 1px;
      border-style: solid;
      border-radius: 6px;

      font-size: var(--u-text-xs-font-size);
      line-height: var(--u-text-xs-line-height);
    }

    .type-default {
      color: var(--u-gray-500);
      background-color: var(--u-gray-50);
      border-color: var(--u-gray-200);
    }

    .type-info {
      color: var(--u-color-info-font);
      background-color: var(--u-color-info-background);
      border-color: var(--u-color-info-border);
    }

    .type-success {
      color: var(--u-color-success-font);
      background-color: var(--u-color-success-background);
      border-color: var(--u-color-success-border);
    }

    .type-warning {
      color: var(--u-color-warning-font);
      background-color: var(--u-color-warning-background);
      border-color: var(--u-color-warning-border);
    }

    .type-error {
      color: var(--u-color-error-font);
      background-color: var(--u-color-error-background);
      border-color: var(--u-color-error-border);
    }
  `;
}

declare global {
  interface HTMLElementTagNameMap {
    "u-tag": UTag;
  }
}

// packages/ui-library/src/components/data-display/Tag/index.vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "UniTag",
});
</script>

<script setup lang="ts">
import { Close } from "@/icons";

withDefaults(
  defineProps<{
    type?: "default" | "success" | "info" | "warning" | "error";
    closable?: boolean;
  }>(),
  {
    type: "default",
  }
);

const emit = defineEmits<{
  (e: "close"): void;
}>();

defineSlots<{
  default(props: {}): any;
}>();

function handleClose() {
  emit("close");
}
</script>

<template>
  <span
    :class="[
      $style.tag,
      $style['tag--type-default'],
      {
        [$style['tag--type-info']]: type === 'info',
        [$style['tag--type-success']]: type === 'success',
        [$style['tag--type-warning']]: type === 'warning',
        [$style['tag--type-error']]: type === 'error',
      },
    ]"
  >
    <slot></slot>

    <Close v-if="closable" :class="$style['close-icon']" @click.stop="handleClose"></Close>
  </span>
</template>

<style lang="scss" module>
@use "@/styles/color";

.tag {
  display: inline-flex;
  align-items: center;
  margin-right: 6px;
  padding: 4px 8px;
  font-size: 12px;
  border-width: 1px;
  border-style: solid;
  border-radius: 6px;
}

.tag--type-default {
  color: color.$gray-500;
  background: color.$gray-50;
  border-color: color.$gray-200;
}

.tag--type-info {
  color: color.$info-font;
  background: color.$info-background;
  border-color: color.$info-border;
}

.tag--type-success {
  color: color.$success-font;
  background: color.$success-background;
  border-color: color.$success-border;
}

.tag--type-error {
  color: color.$error-font;
  background: color.$error-background;
  border-color: color.$error-border;
}

.tag--type-warning {
  color: color.$warning-font;
  background: color.$warning-background;
  border-color: color.$warning-border;
}

.close-icon {
  height: 14px;
  width: 14px;
  margin-left: 6px;
  cursor: pointer;
}
</style>
